project_root: "."
data_dir: "data"
raw_data_dir: "${paths.data_dir}/raw"
interim_data_dir: "${paths.data_dir}/interim"
processed_data_dir: "${paths.data_dir}/processed"
reports_dir: "reports"
figures_dir: "${paths.reports_dir}/figures"
tables_dir: "${paths.reports_dir}/tables"
outputs_dir: "outputs"
