defaults:
  - _self_
  - paths: default
  - mode: train
  - data: example
  - model: example
  - loss: example
  - metrics: example
  - optimizer: example
  - scheduler: null
  - trainer: default
  - callbacks: default
  - logger: default
  - experiment: null

seed: 123
